import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const sellers={pilot:'MarketPilot',npc1:'小明商店',npc2:'3C之家',npc3:'生活百貨'};
const money=value=>`NT$${Math.round(Number(value)||0).toLocaleString('zh-TW')}`;

function App(){
  const [sim,setSim]=useState(null),[agentRun,setAgentRun]=useState(null),[days,setDays]=useState(30),[seed,setSeed]=useState(12345),[running,setRunning]=useState(false),[tab,setTab]=useState(location.hash==='#sim'?'sim':'market'),[selected,setSelected]=useState(null),[search,setSearch]=useState(''),[buyerApi,setBuyerApi]=useState({enabled:false}),[error,setError]=useState('');
  const simulatorRequest=async(path,body)=>{const response=await fetch(`http://127.0.0.1:3001${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),json=await response.json();if(!response.ok)throw new Error(json.error||'模擬器請求失敗');return json};
  const managerRequest=async(path,body)=>{const response=await fetch(`http://127.0.0.1:8000${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined),json=await response.json();if(!response.ok)throw new Error(json.error||'AI 店長請求失敗');return json};
  const refresh=async()=>{try{const [dashboard,status]=await Promise.all([managerRequest('/api/simulator/dashboard'),simulatorRequest('/api/openai')]);setSim(dashboard.state);setAgentRun(dashboard.last_agent_run);setBuyerApi(status);setError('')}catch(requestError){setError(requestError.message)}};
  useEffect(()=>{refresh();const id=setInterval(refresh,2500);return()=>clearInterval(id)},[]);
  useEffect(()=>{if(!running||!sim)return;let cancelled=false;const id=setTimeout(async()=>{try{const result=await managerRequest('/api/simulator/run-day',{});if(!cancelled){setSim(result.state);setAgentRun(result.agent_run);if(result.state.day>=Number(days))setRunning(false)}}catch(runError){if(!cancelled){setError(runError.message);setRunning(false)}}},650);return()=>{cancelled=true;clearTimeout(id)}},[running,sim?.day,days]);
  const reset=async()=>{setRunning(false);try{const result=await managerRequest('/api/simulator/reset',{seed});setSim(result.state);setAgentRun(null);setError('')}catch(resetError){setError(resetError.message)}};
  const setBuyerKey=async apiKey=>{try{setBuyerApi(await simulatorRequest('/api/openai',{apiKey}));setError('')}catch(keyError){setError(keyError.message)}};
  if(!sim)return <main><section className="loading">正在連線至完整市場環境…<p>{error}</p></section></main>;
  const info=Object.fromEntries((sim.catalog||[]).map(product=>[product.id,product])),pilot=sim.listings.filter(listing=>listing.seller==='pilot'&&info[listing.productId]),query=search.toLowerCase(),products=pilot.filter(listing=>info[listing.productId].name.toLowerCase().includes(query)||info[listing.productId].category.includes(search)),visible=selected?pilot.find(listing=>listing.id===selected):null,categories=['全部',...new Set((sim.catalog||[]).map(product=>product.category))],metrics=sim.metrics;
  return <main><header><div className="brand"><span>✦</span><div>MarketPilot <small>智慧電商模擬市場</small></div></div><nav>{[['market','首頁'],['categories','商品分類'],['hot','熱門商品'],['sellers','賣家商店'],['sim','模擬控制台']].map(([id,name])=><button className={tab===id?'active':''} onClick={()=>{setTab(id);location.hash=id==='sim'?'sim':'';setSelected(null)}} key={id}>{name}</button>)}<button className="cart">🛒 購物車 <b>0</b></button></nav></header>
    <section className="hero"><div><p>探索智慧電商的每一天</p><h1>讓策略，創造更好的市場表現</h1><label className="search">⌕ <input value={search} onChange={event=>setSearch(event.target.value)} placeholder="搜尋商品或分類"/></label></div><div className="heroart">🛍️<i>即時市場<br/>模擬中</i></div></section>
    {tab==='sim'?<Simulation {...{sim,agentRun,days,setDays,seed,setSeed,running,setRunning,metrics,pilot,info,reset,buyerApi,setBuyerKey,error}}/>:visible?<Detail listing={visible} product={info[visible.productId]} onBack={()=>setSelected(null)}/>:<><section className="sectionhead"><div><span>精選商品</span><h2>{tab==='sellers'?'MarketPilot 商店':tab==='hot'?'熱門商品排行':tab==='categories'?'全館商品分類':'探索市場上的好商品'}</h2></div><button className="link" onClick={()=>{setTab('sim');location.hash='sim'}}>前往模擬控制台 →</button></section><section className="chips">{categories.map(category=><button key={category} onClick={()=>setSearch(category==='全部'?'':category)}>{category}</button>)}</section><section className="grid">{products.sort((a,b)=>tab==='hot'?b.unitsSold-a.unitsSold:0).map(listing=><Card listing={listing} product={info[listing.productId]} key={listing.id} onClick={()=>setSelected(listing.id)}/>)}</section>{!pilot.length&&<div className="empty">後台尚未建立商品。</div>}<section className="trust"><div>🚚<b>即時市場變化</b><small>交易成果同步到商城</small></div><div>✦<b>可重現模擬</b><small>使用 Random Seed 驗證策略</small></div><div>◌<b>多方賣家競爭</b><small>AI 買家每日決策</small></div></section></>}
  </main>;
}

function Card({listing,product,onClick}){return <article className="card" onClick={onClick}><div className="productimg">{product.emoji}<em>{listing.inventory===0?'已售罄':'現貨供應'}</em></div><div className="cardbody"><small>{product.category}</small><h3>{product.name}</h3><strong>{money(listing.price)}</strong><div className="rating">★ {listing.rating.toFixed(1)} <span>已售出 {listing.unitsSold} 件</span></div><p>賣家：MarketPilot</p></div></article>}

function Detail({listing,product,onBack}){return <section className="detail"><button className="back" onClick={onBack}>← 返回商品列表</button><div className="detailgrid"><div className="detailimg">{product.emoji}</div><div><small>{product.category} · {product.id}</small><h1>{product.name}</h1><h2>{money(listing.price)}</h2><div className="rating big">★ {listing.rating.toFixed(1)} <span>{listing.reviews} 則評價　｜　已售出 {listing.unitsSold} 件</span></div><p>賣家：<b>MarketPilot</b></p><p>庫存：<b>{listing.inventory} 件</b></p><button className="buy">加入購物車</button><button className="buy outline">立即購買</button><hr/><h3>商品介紹</h3><p>{product.description}</p><h3>AI 買家評價</h3>{listing.reviewItems?.length?<div className="reviewlist">{listing.reviewItems.map(review=><article className="review" key={review.id}><span>{review.emoji}</span><div><b>{review.buyer} <small>AI 買家 · 第 {review.day} 天</small></b><em>{'★'.repeat(Math.round(review.score))} <i>{review.score.toFixed(1)}</i></em><p>{review.text}</p></div></article>)}</div>:<p className="muted">尚未收到 AI 買家的評價；開始模擬後會在成交時產生。</p>}</div></div></section>}

function Simulation({sim,agentRun,days,setDays,seed,setSeed,running,setRunning,metrics,pilot,info,reset,buyerApi,setBuyerKey,error}){
  const [key,setKey]=useState(''),active=sim.events||[],max=Math.max(1,...sim.history.map(item=>item.revenue)),decisions=Object.fromEntries((agentRun?.decisions||[]).map(item=>[item.sku,item]));
  return <section className="simulation"><div className="simtop"><div><span>市場模擬引擎</span><h1>模擬控制台</h1><p>在商城直接推進市場，由 GPT 依前一天結果調整價格與促銷。</p></div><div className="status"><i className={running?'pulse':''}></i>{running?'GPT 決策與交易中':sim.day>=days?'模擬完成':'等待開始'}</div></div><div className="keybox"><b>OpenAI 買家</b><span>{buyerApi.enabled?`已啟用（${buyerApi.model}）`:'尚未設定：將使用規則式買家'}</span><input type="password" value={key} onChange={event=>setKey(event.target.value)} placeholder="貼上 OpenAI API Key" autoComplete="off"/><button className="start" disabled={!key} onClick={()=>{setBuyerKey(key);setKey('')}}>啟用 AI 買家</button><small>AI 店長使用後台已設定的 GPT；此金鑰只提供模擬市場買家。</small></div><div className="controls"><label>模擬天數<input type="number" min="1" max="365" value={days} onChange={event=>setDays(Math.max(1,event.target.value))}/></label><label>隨機種子<input type="number" value={seed} onChange={event=>setSeed(event.target.value)}/></label><button className="start" disabled={running||sim.day>=days||!pilot.length} onClick={()=>setRunning(true)}>▶ 開始模擬</button><button onClick={()=>setRunning(false)}>⏸ 暫停</button><button onClick={reset}>↻ 重置</button></div>{error&&<p className="apierror">{error}</p>}<div className="progress"><span>目前進度　第 <b>{sim.day}</b> 天 / {days} 天</span><div><i style={{width:`${Math.min(100,sim.day/days*100)}%`}}/></div></div>
    <div className="metricgrid">{[['總營收',money(metrics.revenue),'↗'],['總利潤',money(metrics.profit),'✦'],['總銷量',`${metrics.units} 件`,'◫'],['市場佔有率',`${metrics.share.toFixed(1)}%`,'◉']].map(([label,value,mark])=><div className="metric" key={label}><i>{mark}</i><small>{label}</small><b>{value}</b></div>)}</div>
    <div className="simgrid"><div className="panel chart"><div className="paneltitle"><div><span>績效趨勢</span><h3>營收趨勢</h3></div><b>{money(metrics.revenue)}</b></div><div className="bars">{sim.history.map(item=><i key={item.day} title={`第 ${item.day} 天：${money(item.revenue)}`} style={{height:`${Math.max(4,item.revenue/max*100)}%`}}/>)}{!sim.history.length&&<p>開始模擬後，這裡會顯示每日營收趨勢。</p>}</div><div className="axis">{sim.history.length?`第 1 天　　　　　　　　　　　　　　　　　第 ${sim.day} 天`:''}</div></div><div className="panel"><div className="paneltitle"><div><span>市場狀態</span><h3>即時市場狀態</h3></div></div><dl><dt>MarketPilot 庫存</dt><dd>{metrics.inventory} 件</dd><dt>市場總銷量</dt><dd>{metrics.marketUnits} 件</dd><dt>商品種類</dt><dd>{pilot.length} 種</dd></dl><h4>目前事件</h4>{active.length?active.map(event=><div className="event" key={event.event_id}>{event.name}<small>剩餘 {event.start_day+event.duration-sim.day} 天</small></div>):<p className="muted">目前沒有市場事件</p>}</div></div>
    <div className="bottomgrid"><div className="panel agent"><div className="paneltitle"><div><span>AI 店長</span><h3>每日價格與促銷決策</h3></div></div><p>所有操作由 GPT 依前一天銷售、競品與事件自動決定。</p>{pilot.map(listing=>{const decision=decisions[listing.productId],competitor=sim.listings.find(item=>item.seller!=='pilot'&&item.productId===listing.productId);return <div className="agentitem" key={listing.id}><b>{info[listing.productId].name}</b><span>{money(listing.price)} · 庫存 {listing.inventory} · 競品 {money(competitor?.price)}</span><small>{decision?.decision?.summary||'等待下一次每日決策'}</small></div>})}</div><div className="panel buyers"><div className="paneltitle"><div><span>AI 買家</span><h3>自主購買與評價</h3></div></div><p>{buyerApi.enabled?'OpenAI 依預算、品類偏好、品質與價格做每日購買決策。':'目前使用規則式買家；設定金鑰後可切換 OpenAI 買家。'}</p><p className="muted">商品頁會顯示 AI 買家的實際短評。</p></div><div className="panel log"><div className="paneltitle"><div><span>活動紀錄</span><h3>模擬紀錄</h3></div></div>{sim.logs.slice(0,10).map((line,index)=><p key={index}>{line}</p>)}</div></div>
    {sim.day>=days&&<div className="result"><span>✦ 模擬完成</span><h2>{days} 天市場策略結果</h2><p>MarketPilot 共創造 <b>{money(metrics.revenue)}</b> 營收、<b>{money(metrics.profit)}</b> 利潤，售出 <b>{metrics.units} 件</b>商品，市場佔有率 {metrics.share.toFixed(1)}%。</p></div>}</section>;
}

createRoot(document.getElementById('root')).render(<App/>);
