import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const catalog = [
  { id:'P001', name:'夏季短袖 T-shirt', category:'服飾', cost:300, quality:.85, description:'100% 純棉材質，透氣舒適，適合夏季日常穿著。', emoji:'👕' },
  { id:'P002', name:'無線藍牙耳機', category:'3C', cost:500, quality:.82, description:'輕巧真無線設計，提供清晰音質與長效續航。', emoji:'🎧' },
  { id:'P003', name:'保溫杯', category:'生活用品', cost:200, quality:.80, description:'雙層真空保溫，讓每一口飲品維持理想溫度。', emoji:'🥤' },
  { id:'P004', name:'精品咖啡豆', category:'食品', cost:350, quality:.90, description:'精選產區阿拉比卡咖啡豆，中焙呈現花果香氣。', emoji:'☕' },
  { id:'P005', name:'運動鞋', category:'服飾', cost:700, quality:.88, description:'輕量避震鞋底，為日常運動提供穩定支撐。', emoji:'👟' },
  { id:'P006', name:'行動電源', category:'3C', cost:450, quality:.84, description:'10000mAh 高效充電，外出旅行的可靠電力夥伴。', emoji:'🔋' },
];
const info = Object.fromEntries(catalog.map(p=>[p.id,p]));
const initialListings = [
  ['npc1','P001',479,110,4.6,192], ['npc1','P005',1090,65,4.7,86],
  ['npc2','P002',799,95,4.6,128], ['npc2','P006',699,90,4.5,91],
  ['npc3','P003',379,140,4.5,152], ['npc3','P004',559,75,4.8,105],
].map(([seller,productId,price,inventory,rating,unitsSold])=>({id:`${seller}-${productId}`,seller,productId,price,inventory,initialInventory:inventory,rating,reviews:Math.round(unitsSold*.55),unitsSold,revenue:price*unitsSold,profit:(price-info[productId].cost)*unitsSold, restocked:0,reviewItems:[]}));
const sellers = { pilot:'MarketPilot', npc1:'小明商店', npc2:'3C之家', npc3:'生活百貨' };
const aiBuyers = [
  {name:'小安',emoji:'🧑🏻‍💻',budget:1.15,likes:['3C','服飾'],tone:'理性'},
  {name:'雅婷',emoji:'👩🏻',budget:1.35,likes:['生活用品','食品'],tone:'溫暖'},
  {name:'阿哲',emoji:'🧑🏻',budget:.95,likes:['3C','服飾'],tone:'精打細算'},
  {name:'米米',emoji:'🧑🏼‍🎨',budget:1.25,likes:['服飾','食品'],tone:'細節派'},
  {name:'志豪',emoji:'👨🏻',budget:1.5,likes:['生活用品','3C'],tone:'務實'},
];
function seeded(seed){ let s=(Number(seed)||1)>>>0; return ()=>{s=(s*1664525+1013904223)>>>0; return s/4294967296} }
function createState(seed){return {day:0, seed, listings:structuredClone(initialListings), logs:['市場已準備完成：NPC 賣家已上架 6 項商品。'], aiBuyerLog:['AI 買家已就緒，將依預算、偏好、品質與售價自主決策。'], events:[], history:[], completed:false, pendingActions:[]}}
function activeDemand(state, product){ let factor=1; state.events.filter(e=>state.day>=e.start_day&&state.day<e.start_day+e.duration).forEach(e=>{if(!e.category||e.category===product.category)factor*=e.effect}); return factor }
function metrics(state){ const mine=state.listings.filter(x=>x.seller==='pilot'); const market=state.listings.reduce((a,x)=>a+x.unitsSold,0); const revenue=mine.reduce((a,x)=>a+x.revenue,0), profit=mine.reduce((a,x)=>a+x.profit,0), units=mine.reduce((a,x)=>a+x.unitsSold,0); return {revenue,profit,units,inventory:mine.reduce((a,x)=>a+x.inventory,0),share:market?units/market*100:0,rating:mine.length?mine.reduce((a,x)=>a+x.rating,0)/mine.length:0,marketUnits:market} }
function eventFor(day,r){ if(r()>.31) return null; const opts=[{name:'🔥 市場需求暴增',effect:1.3,duration:2},{name:'📉 市場需求下降',effect:.7,duration:2},{name:'🔥 服飾類突然熱門',effect:1.35,duration:3,category:'服飾'},{name:'🛍️ 購物節',effect:1.45,duration:1}]; const e=opts[Math.floor(r()*opts.length)]; return {...e,event_id:`E${day}`,start_day:day} }
function reviewText(buyer,p,score,price){ const priceNote=price<=p.cost*1.45?'價格很合理':'整體仍符合期待'; const lines=score>=4.7?[`品質比預期更好，${priceNote}。`,`使用感受很滿意，會考慮再次購買。`]:score>=4?[`商品和描述相符，${priceNote}。`,`整體表現穩定，這次購買很順利。`]:[`商品基本符合需求，希望包裝與細節能再提升。`,`可以使用，但和預期仍有一點差距。`]; return lines[Math.floor((score*10+price)%lines.length)] }
function aiPurchase(buyer,p,l,r){ const preference=buyer.likes.includes(p.category)?.22:0; const affordability=Math.min(1.25,(p.cost*buyer.budget*1.7)/l.price); const value=(p.quality*1.05)+affordability*.7+preference+(r()-.5)*.28; const score=Math.max(3,Math.min(5,p.quality*4.15+affordability*.62+preference*.65+(r()-.5)*.55)); return {value,score}; }
function step(old){ const state=structuredClone(old), r=seeded(Number(state.seed)+state.day*7919); state.day++; const logs=[`Day ${state.day}`];
  const ev=eventFor(state.day,r); if(ev){state.events.push(ev);logs.push(`${ev.name}｜需求 ${ev.effect>1?'+':'-'}${Math.round(Math.abs(ev.effect-1)*100)}%`)}
  // NPC strategy: competitive products gently adjust then restock low inventory
  state.listings.filter(l=>l.seller!=='pilot').forEach(l=>{const peers=state.listings.filter(x=>x.productId===l.productId&&x.id!==l.id); if(peers.length&&r()<.38){const avg=peers.reduce((a,x)=>a+x.price,0)/peers.length; const target=Math.round(avg*.98); if(target!==l.price){l.price=target;logs.push(`${sellers[l.seller]} 調整「${info[l.productId].name}」價格為 NT$${target}`)}} if(l.inventory<20&&r()<.7){l.inventory+=60;l.restocked+=60;logs.push(`${sellers[l.seller]} 補貨「${info[l.productId].name}」60 件`)}});
  state.pendingActions.forEach(a=>{const p=info[a.productId]; let l=state.listings.find(x=>x.seller==='pilot'&&x.productId===a.productId); if(a.type==='list_product'&&p&&!l&&a.price>p.cost&&a.initial_inventory>0){state.listings.push(l={id:`pilot-${a.productId}`,seller:'pilot',productId:a.productId,price:a.price,inventory:a.initial_inventory,initialInventory:a.initial_inventory,rating:4.5,reviews:0,unitsSold:0,revenue:0,profit:0,restocked:0,reviewItems:[]});logs.push(`MarketPilot 上架「${p.name}」｜售價 NT$${a.price}｜庫存 ${a.initial_inventory}`)} else if(a.type==='update_price'&&l&&a.price>p.cost){l.price=a.price;logs.push(`MarketPilot 更新「${p.name}」價格為 NT$${a.price}`)} else if(a.type==='restock'&&l&&a.quantity>0){l.inventory+=a.quantity;l.restocked+=a.quantity;logs.push(`MarketPilot 補貨「${p.name}」${a.quantity} 件`)} else if(a.type==='delist_product'&&l){state.listings=state.listings.filter(x=>x!==l);logs.push(`MarketPilot 下架「${p.name}」`)} else logs.push(`MarketPilot 動作未通過驗證：${a.type}`)}); state.pendingActions=[];
  const buyerLog=[];
  state.listings.forEach(l=>{if(!l.inventory)return;const p=info[l.productId]; const priceFactor=Math.max(.15,1.75-l.price/(p.cost*1.55));const ratingFactor=.65+l.rating/5*.55;const demand=13*priceFactor*(.65+p.quality*.55)*ratingFactor*activeDemand(state,p)*(.65+r()*.7);const candidates=Array.from({length:Math.max(0,Math.round(demand))},()=>{const buyer=aiBuyers[Math.floor(r()*aiBuyers.length)];return {buyer,...aiPurchase(buyer,p,l,r)}}).filter(x=>x.value>=1.28+r()*.18);const sold=Math.min(l.inventory,candidates.length);if(sold){l.inventory-=sold;l.unitsSold+=sold;l.revenue+=sold*l.price;l.profit+=sold*(l.price-p.cost); const newReviews=Math.round(sold*(.38+r()*.18));candidates.slice(0,newReviews).forEach(({buyer,score},i)=>{score=Math.round(score*10)/10;l.rating=(l.rating*l.reviews+score)/(l.reviews+1);l.reviews++;const review={id:`${state.day}-${l.id}-${i}`,buyer:buyer.name,emoji:buyer.emoji,score,text:reviewText(buyer,p,score,l.price),day:state.day};l.reviewItems=[review,...(l.reviewItems||[])].slice(0,8);buyerLog.push(`${buyer.emoji} ${buyer.name} 購買「${p.name}」並留下 ${score.toFixed(1)} 星評價`)}); if(l.seller==='pilot')logs.push(`MarketPilot 售出 ${sold} 件「${p.name}」`)}});
  state.aiBuyerLog=[...buyerLog,...state.aiBuyerLog].slice(0,24);
  state.events=state.events.filter(e=>state.day<e.start_day+e.duration); const m=metrics(state); state.history.push({day:state.day,...m,transactions:state.listings.reduce((a,l)=>a+l.unitsSold,0)}); state.logs=[...logs,...state.logs].slice(0,80); return state }
function money(n){return `NT$${Math.round(n).toLocaleString('zh-TW')}`}
function App(){ const [sim,setSim]=useState(null);const [days,setDays]=useState(30);const [seed,setSeed]=useState(12345);const [running,setRunning]=useState(false);const [tab,setTab]=useState('market');const [selected,setSelected]=useState(null);const [search,setSearch]=useState('');const [action,setAction]=useState({productId:'P001',price:499,initial_inventory:100});const [api,setApi]=useState({enabled:false});const [error,setError]=useState('');
 const request=async(path,body)=>{const r=await fetch(`http://localhost:3001${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const json=await r.json();if(!r.ok)throw new Error(json.error||'API request failed');return json};
 const refresh=async()=>{try{setSim(await request('/api/state'));setApi(await request('/api/openai'));setError('')}catch{setError('無法連線至 API；請在另一個終端執行 npm run api。')}};
 useEffect(()=>{refresh();const id=setInterval(refresh,2000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!running||!sim)return;let cancelled=false;const id=setTimeout(async()=>{try{const next=await request('/api/step',{days:1});if(!cancelled){setSim(next);if(next.day>=Number(days))setRunning(false)}}catch(e){if(!cancelled){setError(e.message);setRunning(false)}}},650);return()=>{cancelled=true;clearTimeout(id)}},[running,sim?.day,days]);
 const queue=async(a)=>{try{await request('/api/actions',a);await refresh()}catch(e){setError(e.message)}};const reset=async()=>{setRunning(false);try{setSim(await request('/api/reset',{seed}));setError('')}catch(e){setError(e.message)}};const setKey=async apiKey=>{try{setApi(await request('/api/openai',{apiKey}));setError('')}catch(e){setError(e.message)}};
 if(!sim)return <main><section className="loading">正在連線至本機 API…<p>{error}</p></section></main>;const m=sim.metrics;const products=sim.listings.filter(l=>info[l.productId].name.toLowerCase().includes(search.toLowerCase())||info[l.productId].category.includes(search));const pilot=sim.listings.filter(l=>l.seller==='pilot'); const visible=selected?sim.listings.find(x=>x.id===selected):null;
 return <main><header><div className="brand"><span>✦</span><div>MarketPilot <small>智慧電商模擬市場</small></div></div><nav>{[['market','首頁'],['categories','商品分類'],['hot','熱門商品'],['sellers','賣家商店'],['sim','模擬控制台']].map(([id,name])=><button className={tab===id?'active':''} onClick={()=>{setTab(id);setSelected(null)}} key={id}>{name}</button>)}<button className="cart">🛒 購物車 <b>0</b></button></nav></header>
 <section className="hero"><div><p>探索智慧電商的每一天</p><h1>讓策略，創造更好的市場表現</h1><label className="search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜尋商品或分類"/></label></div><div className="heroart">🛍️<i>即時市場<br/>模擬中</i></div></section>
 {tab==='sim'?<Simulation {...{sim,days,setDays,seed,setSeed,running,setRunning,m,action,setAction,queue,pilot,reset,api,setKey,error}}/>:visible?<Detail l={visible} onBack={()=>setSelected(null)} />:<><section className="sectionhead"><div><span>精選商品</span><h2>{tab==='sellers'?'MarketPilot 商店':tab==='hot'?'熱門商品排行':tab==='categories'?'全館商品分類':'探索市場上的好商品'}</h2></div><button className="link" onClick={()=>setTab('sim')}>前往模擬控制台 →</button></section><section className="chips">{['全部','服飾','3C','生活用品','食品'].map(c=><button key={c} onClick={()=>setSearch(c==='全部'?'':c)}>{c}</button>)}</section><section className="grid">{(tab==='sellers'?pilot:products).sort((a,b)=>tab==='hot'?b.unitsSold-a.unitsSold:0).map(l=><Card l={l} key={l.id} onClick={()=>setSelected(l.id)}/>)}</section>{tab==='sellers'&&!pilot.length&&<div className="empty">MarketPilot 尚未上架商品。請到「模擬控制台」使用 Agent 動作上架。</div>}<section className="trust"><div>🚚<b>即時市場變化</b><small>交易成果同步到商城</small></div><div>✦<b>可重現模擬</b><small>使用 Random Seed 驗證策略</small></div><div>◌<b>多方賣家競爭</b><small>AI 買家每日決策</small></div></section></>}
 </main> }
function Card({l,onClick}){const p=info[l.productId];return <article className="card" onClick={onClick}><div className="productimg">{p.emoji}<em>{l.inventory===0?'已售罄':'現貨供應'}</em></div><div className="cardbody"><small>{p.category}</small><h3>{p.name}</h3><strong>{money(l.price)}</strong><div className="rating">★ {l.rating.toFixed(1)} <span>已售出 {l.unitsSold} 件</span></div><p>賣家：{sellers[l.seller]}</p></div></article>}
function Detail({l,onBack}){const p=info[l.productId];return <section className="detail"><button className="back" onClick={onBack}>← 返回商品列表</button><div className="detailgrid"><div className="detailimg">{p.emoji}</div><div><small>{p.category} · {p.id}</small><h1>{p.name}</h1><h2>{money(l.price)}</h2><div className="rating big">★ {l.rating.toFixed(1)} <span>{l.reviews} 則評價　｜　已售出 {l.unitsSold} 件</span></div><p>賣家：<b>{sellers[l.seller]}</b></p><p>庫存：<b>{l.inventory} 件</b></p><button className="buy">加入購物車</button><button className="buy outline">立即購買</button><hr/><h3>商品介紹</h3><p>{p.description}</p><h3>AI 買家評價</h3>{l.reviewItems?.length?<div className="reviewlist">{l.reviewItems.map(x=><article className="review" key={x.id}><span>{x.emoji}</span><div><b>{x.buyer} <small>AI 買家 · 第 {x.day} 天</small></b><em>{'★'.repeat(Math.round(x.score))} <i>{x.score.toFixed(1)}</i></em><p>{x.text}</p></div></article>)}</div>:<p className="muted">尚未收到 AI 買家的評價；開始模擬後會在成交時產生。</p>}</div></div></section>}
function Simulation({sim,days,setDays,seed,setSeed,running,setRunning,m,action,setAction,queue,pilot,reset,api,setKey,error}){const [key,setKeyValue]=useState('');const active=sim.events;const max=Math.max(1,...sim.history.map(x=>x.revenue));return <section className="simulation"><div className="simtop"><div><span>市場模擬引擎</span><h1>模擬控制台</h1><p>管理市場條件、Agent 策略，並觀察每一天的成果。</p></div><div className="status"><i className={running?'pulse':''}></i>{running?'模擬運行中':sim.day>=days?'模擬完成':'等待開始'}</div></div><div className="keybox"><b>OpenAI 買家</b><span>{api.enabled?`已啟用（${api.model}）`:'尚未設定：將使用規則式買家'}</span><input type="password" value={key} onChange={e=>setKeyValue(e.target.value)} placeholder="貼上 OpenAI API Key" autoComplete="off"/><button className="start" disabled={!key} onClick={()=>{setKey(key);setKeyValue('')}}>啟用 AI 買家</button><small>金鑰只保留在本機 API 程序記憶體，重啟後即清除。</small></div><div className="controls"><label>模擬天數<input type="number" min="1" max="365" value={days} onChange={e=>setDays(Math.max(1,e.target.value))}/></label><label>隨機種子<input type="number" value={seed} onChange={e=>setSeed(e.target.value)}/></label><button className="start" disabled={running||sim.day>=days} onClick={()=>setRunning(true)}>▶ 開始模擬</button><button onClick={()=>setRunning(false)}>⏸ 暫停</button><button onClick={reset}>↻ 重置</button></div>{error&&<p className="apierror">{error}</p>}<div className="progress"><span>目前進度　第 <b>{sim.day}</b> 天 / {days} 天</span><div><i style={{width:`${Math.min(100,sim.day/days*100)}%`}}/></div></div>
 <div className="metricgrid">{[['總營收',money(m.revenue),'↗'],['總利潤',money(m.profit),'✦'],['總銷量',`${m.units} 件`,'◫'],['市場佔有率',`${m.share.toFixed(1)}%`,'◉']].map(([a,b,c])=><div className="metric" key={a}><i>{c}</i><small>{a}</small><b>{b}</b></div>)}</div>
 <div className="simgrid"><div className="panel chart"><div className="paneltitle"><div><span>績效趨勢</span><h3>營收趨勢</h3></div><b>{money(m.revenue)}</b></div><div className="bars">{sim.history.map(x=><i key={x.day} title={`第 ${x.day} 天：${money(x.revenue)}`} style={{height:`${Math.max(4,x.revenue/max*100)}%`}}/>)}{!sim.history.length&&<p>開始模擬後，這裡會顯示每日營收趨勢。</p>}</div><div className="axis">{sim.history.length?`第 1 天　　　　　　　　　　　　　　　　　第 ${sim.day} 天`:''}</div></div><div className="panel"><div className="paneltitle"><div><span>市場狀態</span><h3>即時市場狀態</h3></div></div><dl><dt>MarketPilot 庫存</dt><dd>{m.inventory} 件</dd><dt>市場總銷量</dt><dd>{m.marketUnits} 件</dd><dt>平均商品評價</dt><dd>{m.rating?`★ ${m.rating.toFixed(2)}`:'—'}</dd></dl><h4>目前事件</h4>{active.length?active.map(e=><div className="event" key={e.event_id}>{e.name}<small>剩餘 {e.start_day+e.duration-sim.day} 天</small></div>):<p className="muted">目前沒有市場事件</p>}</div></div>
 <div className="bottomgrid"><div className="panel agent"><div className="paneltitle"><div><span>Agent 介面</span><h3>MarketPilot Agent 動作</h3></div></div><p>從固定商品目錄建立合法動作；動作會在下一個模擬日套用。</p><div className="form"><select value={action.productId} onChange={e=>{let p=info[e.target.value];setAction({...action,productId:e.target.value,price:Math.round(p.cost*1.55)})}}>{catalog.map(p=><option key={p.id} value={p.id}>{p.name}（成本 {money(p.cost)}）</option>)}</select><input type="number" value={action.price} onChange={e=>setAction({...action,price:+e.target.value})}/><input type="number" value={action.initial_inventory} onChange={e=>setAction({...action,initial_inventory:+e.target.value})}/><button className="start" onClick={()=>queue({type:'list_product',...action})}>上架商品</button></div>{pilot.map(l=><div className="agentitem" key={l.id}><b>{info[l.productId].name}</b><span>{money(l.price)} · 庫存 {l.inventory}</span><button onClick={()=>queue({type:'restock',productId:l.productId,quantity:100})}>補貨 100</button><button onClick={()=>queue({type:'update_price',productId:l.productId,price:l.price+20})}>調高價格</button></div>)}</div><div className="panel buyers"><div className="paneltitle"><div><span>AI 買家</span><h3>自主購買與評價</h3></div></div><p>{api.enabled?'OpenAI 依預算、品類偏好、品質與價格做每日購買決策。':'尚未設定 API Key，目前使用規則式買家。'}</p><p className="muted">商品頁會顯示 AI 買家的實際短評。</p></div><div className="panel log"><div className="paneltitle"><div><span>活動紀錄</span><h3>模擬紀錄</h3></div></div>{sim.logs.slice(0,10).map((x,i)=><p key={i}>{x}</p>)}</div></div>
 {sim.day>=days&&<div className="result"><span>✦ 模擬完成</span><h2>{days} 天市場策略結果</h2><p>MarketPilot 共創造 <b>{money(m.revenue)}</b> 營收、<b>{money(m.profit)}</b> 利潤，售出 <b>{m.units} 件</b>商品，市場佔有率 {m.share.toFixed(1)}%。</p></div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
